python train.py \
--subslices /auto/k1/carson/glab/mrf/train_data_list.npy  \
--name mrf \
--model pix2pix \
--dataroot /home/jlg/carson/Desktop/mrf_dataset \
--align_data \
--which_model_netG unet_128 \
--which_direction AtoB \
--lambda_A 10 \
--no_lsgan \
--use_dropout \
--laploss 0.001 \
--input_nc 498 \
--output_nc 3 \
--batchSize 16 \
--print_freq 10
